name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag basedradio:$(date +%s)
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: rpgwaiter
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rpgwaiter/basedradio:latest
