name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Builder
      run: docker build . --file Dockerfile.builder --tag builder:$(date +%s)
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag basedradio:$(date +%s)
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rpgwaiter/basedradio
        tag_with_ref: true
